from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import httpx


@dataclass(slots=True)
class DiagnosisResult:
    root_cause: str
    confidence_score: float


@dataclass(slots=True)
class FixResult:
    action: str
    suggested_fix: str
    rationale: str
    confidence_score: float


class LLMClient:
    def __init__(
        self,
        *,
        api_key: str | None,
        base_url: str,
        model: str,
        timeout_seconds: float = 20.0,
    ) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout_seconds = timeout_seconds

    def diagnose(self, context: dict[str, Any]) -> DiagnosisResult:
        payload = {
            "task": "diagnose",
            "issue_type": context.get("issue_type"),
            "signals": context.get("signals", []),
            "logs": context.get("logs", ""),
            "retry_count": context.get("retry_count", 0),
            "history": context.get("history", []),
        }
        response = self._complete_json(payload)
        if response is None:
            return self._fallback_diagnosis(context)
        return DiagnosisResult(
            root_cause=response.get("root_cause", self._fallback_diagnosis(context).root_cause),
            confidence_score=float(response.get("confidence_score", 0.6)),
        )

    def suggest_fix(self, context: dict[str, Any]) -> FixResult:
        payload = {
            "task": "suggest_fix",
            "issue_type": context.get("issue_type"),
            "root_cause": context.get("root_cause"),
            "available_actions": context.get("available_actions", []),
            "retry_count": context.get("retry_count", 0),
            "history": context.get("history", []),
        }
        response = self._complete_json(payload)
        if response is None:
            return self._fallback_fix(context)
        return FixResult(
            action=response.get("action", "no_action"),
            suggested_fix=response.get("suggested_fix", "No safe fix available."),
            rationale=response.get("rationale", "Generated by LLM."),
            confidence_score=float(response.get("confidence_score", 0.6)),
        )

    def _complete_json(self, payload: dict[str, Any]) -> dict[str, Any] | None:
        if not self.api_key:
            return None
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        messages = [
            {
                "role": "system",
                "content": (
                    "You are an incident response assistant. Reply with valid JSON only. "
                    "For diagnose return root_cause and confidence_score. "
                    "For suggest_fix return action, suggested_fix, rationale, confidence_score."
                ),
            },
            {"role": "user", "content": json.dumps(payload)},
        ]
        request_body = {"model": self.model, "messages": messages, "temperature": 0}
        try:
            with httpx.Client(timeout=self.timeout_seconds) as client:
                response = client.post(
                    f"{self.base_url}/chat/completions",
                    headers=headers,
                    json=request_body,
                )
                response.raise_for_status()
                body = response.json()
                content = body["choices"][0]["message"]["content"]
                return json.loads(content)
        except (httpx.HTTPError, KeyError, IndexError, json.JSONDecodeError, TypeError, ValueError):
            return None

    def _fallback_diagnosis(self, context: dict[str, Any]) -> DiagnosisResult:
        issue_type = context.get("issue_type", "unknown")
        signals = ", ".join(context.get("signals", []))
        if issue_type == "database":
            root_cause = "Database connection pool exhaustion is causing request failures."
        elif issue_type == "network":
            root_cause = "Network instability or DNS resolution failures are interrupting upstream calls."
        elif issue_type == "infrastructure":
            root_cause = "Infrastructure capacity pressure is degrading service health."
        elif issue_type == "application_bug":
            root_cause = "An application-level defect or bad deployment is triggering repeated exceptions."
        else:
            root_cause = f"Likely issue inferred from log signals: {signals or 'unknown'}."
        return DiagnosisResult(root_cause=root_cause, confidence_score=0.58)

    def _fallback_fix(self, context: dict[str, Any]) -> FixResult:
        issue_type = context.get("issue_type", "unknown")
        retry_count = context.get("retry_count", 0)
        if issue_type == "database":
            action = "restart_service" if retry_count == 0 else "scale_worker_pool"
            fix = "Restart the database-facing service to refresh connections." if retry_count == 0 else "Scale the worker pool to reduce database queue pressure."
        elif issue_type == "network":
            action = "retry_request"
            fix = "Retry outbound requests after transient network failure."
        elif issue_type == "infrastructure":
            action = "scale_worker_pool"
            fix = "Scale the worker pool to recover from resource saturation."
        elif issue_type == "application_bug":
            action = "rollback_release" if retry_count == 0 else "restart_service"
            fix = "Roll back the latest release to remove the faulty code path." if retry_count == 0 else "Restart the service after rollback validation."
        else:
            action = "restart_service"
            fix = "Restart the impacted service as the safest broad remediation."
        return FixResult(
            action=action,
            suggested_fix=fix,
            rationale="Deterministic fallback policy selected the safest available action.",
            confidence_score=0.55,
        )
